services:
  kafka:
    image: apache/kafka:3.7.1
    container_name: kraft-kafka
    ports:
      - "9092:9092"
    environment:
      # KRaft single-node broker+controller
      KAFKA_NODE_ID: "1"
      KAFKA_CLUSTER_ID: "q1Sh-9_ISia_zwGINzRvyQ"
      KAFKA_PROCESS_ROLES: "broker,controller"
      KAFKA_CONTROLLER_QUORUM_VOTERS: "1@kafka:9093"
      KAFKA_LISTENERS: "PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093"
      KAFKA_ADVERTISED_LISTENERS: "PLAINTEXT://localhost:9092"
      KAFKA_CONTROLLER_LISTENER_NAMES: "CONTROLLER"
      KAFKA_INTER_BROKER_LISTENER_NAME: "PLAINTEXT"
      # Single broker => replication factor 1
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: "1"
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: "1"
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: "1"
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: "0"
      # Allow topic create via AdminClient
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "false"
    healthcheck:
      test: ["CMD-SHELL", "/opt/kafka/bin/kafka-broker-api-versions.sh --bootstrap-server localhost:9092 >/dev/null 2>&1"]
      interval: 5s
      timeout: 5s
      retries: 20

  postgres:
    image: postgres:16-alpine
    container_name: kraft-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: kraft_demo
      POSTGRES_USER: kraft
      POSTGRES_PASSWORD: kraft
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U kraft -d kraft_demo >/dev/null 2>&1"]
      interval: 5s
      timeout: 5s
      retries: 20
